{% set name = "ouroboros-gis" %}
{% set version = "1.0.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ouroboros_gis-{{ version }}.tar.gz
  sha256: ef2351540fc5fb5087e04abcd574eb04128cf632e0e54dbcce21f0295816969c

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - gdal >=3.8
        - geojson
        - geopandas
        - libsqlite >=3.37
        - matplotlib-base
        - sqlite >=3.37
        - xmltodict

    test:
      imports:
        - ouroboros
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: ouroboros
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - ouroboros

about:
  home: https://github.com/corbel-spatial/ouroboros
  summary: Towards more pythonic use of GeoDatabases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-vdp
