{% set name = "ouroboros-gis" %}
{% set version = "1.0.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ouroboros_gis-{{ version }}.tar.gz
  sha256: f65d3ddf0a23bd5bbca1ed31095b34482cf52cc601eba5f58d892c72c4cdcb46

build:
  number: 3

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv

    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - gdal >=3.8
        - geojson
        - geopandas >=1.0
        - libsqlite >=3.37
        - matplotlib-base
        - pyogrio
        - sqlite >=3.37
        - xmltodict

    test:
      imports:
        - ouroboros
      commands:
        - pip check
        - python -c "from osgeo import gdal; print(gdal.__version__)"
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://github.com/corbel-spatial/ouroboros
  summary: Pythonic use of GeoDatabases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-vdp
